
services:
  app:
    build:
      context: ./backend-avanzada-go-main
    container_name: backend-go-app
    env_file: ./.env
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:bookworm
    restart: always
    container_name: backend-go-db
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: [CMD-SHELL, "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql

  frontend:
    build:
      context: ./frontend-avanzada-final
    container_name: frontend-app
    ports:
      - 5173:5173
    env_file:
      - ./.env
    depends_on:
      - app

volumes:
  pg-data:
